"""Tests holding `docs/formal.md` to the code and claim-to-test map.

The bibliography registry is in `docs/theory/bibliography.md`.

What this module is for:
  `docs/formal.md` states the mathematics of this tool once, in one notation. Three things have to
  be true of it, and none of them survives being asked for politely:

  1. Every `test_*` it names resolves to a test that exists — the discipline
     `tests/test_docs_semantics.py` already applies to `docs/semantics.md`.
  2. Every definition the code also defines is **generated from the code** and compared, so the
     document cannot be edited into disagreement with `Strength`, `BASIS_RUNGS`,
     `rulelang.FRAGMENTS` or `manyvalued.ALGEBRAS`. Three documents each held to the code cannot
     drift apart from each other, which is what makes a fourth document safe to add.
  3. The bibliography in `docs/theory/bibliography.md` is a **registry**: every citation key used
     anywhere in the scanned corpus
     resolves to an entry, every entry is cited by at least one claim, and a source named without a
     key fails the build. This is the new part. Before it, the densest concentration of references
     in the tree was inside `src/reasonsmith/verdict.py`, where nobody looking for a bibliography
     would find them, and nothing stopped the next one landing there too.

What a reader must not break:
  - The generated comparisons must stay generated. Writing the expected chain, table or name list
    as a literal here would move the drift one file over rather than removing it.
  - `SCANNED_EXCLUSIONS` is the corpus boundary and every member is excluded for a stated reason
    (`docs/formal.md`, *The registry*). Widening the corpus is a one-line change; narrowing it
    silently is what the list exists to prevent.
  - Check 3 is a heuristic over a venue-marker list and the other two are not. Deleting a marker
    weakens it invisibly, which is why `VENUE_MARKERS` is asserted non-empty and the document says
    in as many words what the check does not catch.
"""

from __future__ import annotations

import ast
import dataclasses
import re
from pathlib import Path

from reasonsmith.manyvalued import ALGEBRAS
from reasonsmith.rulelang import FRAGMENTS
from reasonsmith.spec import Requirement
from reasonsmith.verdict import BASIS_RUNGS, Strength

REPO_ROOT = Path(__file__).resolve().parent.parent
TESTS_DIR = REPO_ROOT / "tests"
DOCS_DIR = REPO_ROOT / "docs"
FORMAL = DOCS_DIR / "formal.md"
MODELS = DOCS_DIR / "theory" / "01-models.md"
SYNTAX = DOCS_DIR / "theory" / "02-syntax.md"
SEMANTICS = DOCS_DIR / "theory" / "03-semantics.md"
PROCEDURES = DOCS_DIR / "theory" / "05-decision-procedures.md"
BIBLIOGRAPHY = DOCS_DIR / "theory" / "bibliography.md"
ENGINES_DIR = REPO_ROOT / "src" / "reasonsmith" / "engines"

#: A `test_...` identifier as the document writes them. A name followed by `.py` is a module the
#: document points at, not a claim's enforcing test.
_TEST_NAME = re.compile(r"\btest_[a-z0-9_]+\b(?!\.py)")

#: A citation, in the one form the document's key convention admits: a backticked, pandoc-style
#: `[@key]`. The at-sign is what keeps this off `[grading] algebra` and off a markdown link, and
#: the surrounding backticks are what keep it off `details[PROBE_BUDGET_KEY]`.
_CITATION_KEY = re.compile(r"`\[@([a-z][a-z0-9-]*)\]`")

#: A bibliography entry, which is a list item whose first token is its own key in bold.
_BIBLIOGRAPHY_ENTRY = re.compile(r"^- \*\*`\[@([a-z][a-z0-9-]*)\]`\*\*")

#: Files inside the scanned directories that carry no citable prose. Each is excluded for a reason
#: `docs/formal.md` states; none is excluded because keying it was inconvenient.
SCANNED_EXCLUSIONS = (
    "example-output.md",  # generated byte-for-byte by a builder
    "nesyarena-conformance-report.md",  # generated byte-for-byte by a builder
    "legal-sources.md",  # statutory retrieval record; its sources are laws, tracked by drift.py
)

#: Publication-venue markers. A block of prose carrying one of these and no citation key is a
#: source that landed without being registered. The list is deliberately conservative: every entry
#: is a venue this repository actually cites, because a marker that fires on ordinary prose is a
#: check somebody switches off.
VENUE_MARKERS = (
    "AAAI",
    "NeurIPS",
    "IJCAI",
    "ECAI",
    "CSFW",
    "TABLEAUX",
    "AIxIA",
    "CHARME",
    "ACL 20",
    "SAS 20",
    "JAIR",
    "Kluwer",
    "et al.",
    "LNCS",
    "Information Processing Letters",
    "Journal of Computer Security",
    "Journal of Artificial Intelligence Research",
    "Annals of Mathematics and Artificial Intelligence",
    "Artificial Intelligence and Law",
    "Formal Methods in System Design",
    "Trends in Logic",
    "Software Tools for Technology Transfer",
    "Transactions on Software Engineering and Methodology",
)

#: Cardinal numbers as the document writes them (prose, not numerals).
_NUMBER_WORDS = (
    "zero", "one", "two", "three", "four", "five", "six", "seven", "eight", "nine",
    "ten", "eleven", "twelve", "thirteen", "fourteen", "fifteen", "sixteen",
    "seventeen", "eighteen", "nineteen", "twenty",
)


def _document() -> str:
    assert FORMAL.is_file(), f"{FORMAL} does not exist"
    return FORMAL.read_text(encoding="utf-8")


def _scanned_files() -> list[Path]:
    """The corpus the registry is enforced over: documentation prose and package sources."""
    files = [p for p in sorted(DOCS_DIR.rglob("*.md")) if p.name not in SCANNED_EXCLUSIONS]
    files += sorted((REPO_ROOT / "src" / "reasonsmith").rglob("*.py"))
    return files


def _bibliography_keys() -> dict[str, str]:
    """Every key the bibliography defines, mapped to the line that defines it."""
    keys: dict[str, str] = {}
    for line in BIBLIOGRAPHY.read_text(encoding="utf-8").splitlines():
        match = _BIBLIOGRAPHY_ENTRY.match(line)
        if match:
            keys[match.group(1)] = line
    return keys


def _defined_test_names() -> set[str]:
    """Every test function name this suite defines, read from the sources rather than collected."""
    names: set[str] = set()
    for path in sorted(TESTS_DIR.glob("test_*.py")):
        tree = ast.parse(path.read_text(encoding="utf-8"), filename=str(path))
        for node in ast.walk(tree):
            if isinstance(node, (ast.FunctionDef, ast.AsyncFunctionDef)) and node.name.startswith(
                "test_"
            ):
                names.add(node.name)
    return names


def _section(title: str, path: Path = FORMAL) -> str:
    """The text of one heading in a document, up to the next heading of equal level."""
    document = path.read_text(encoding="utf-8")
    start = document.index(title)
    rest = document[start + len(title) :]
    end = rest.find("\n## ")
    return rest if end < 0 else rest[:end]


# ------------------------------------------------------------------------------------------------
# 1. The claim-to-test map
# ------------------------------------------------------------------------------------------------


def test_the_formal_doc_is_linked_from_the_docs_index():
    """A document nobody can find answers nobody's question."""
    assert FORMAL.is_file()
    assert "formal.md" in (DOCS_DIR / "README.md").read_text(encoding="utf-8")


def test_every_test_named_in_the_formal_doc_exists():
    """The claim-to-test map is the document's warrant; a dangling name voids it."""
    named = set(_TEST_NAME.findall(_document()))
    assert named, "the document names no test, so nothing in it is enforced"

    missing = sorted(named - _defined_test_names())
    assert not missing, (
        "docs/formal.md names test(s) that do not exist in tests/: "
        + ", ".join(missing)
        + ". Rename the claim's test back, or cut the claim."
    )


# ------------------------------------------------------------------------------------------------
# 2. Definitions the code also defines, generated and compared
# ------------------------------------------------------------------------------------------------


def test_the_formal_doc_states_the_chain_the_code_defines():
    """§4.1's ordering sentence is generated from `Strength`, not written from memory."""
    chain = " < ".join(s.value for s in sorted(Strength))
    assert chain == "unattainable < observed < recounted < probed < proved"
    assert chain in _document(), (
        "docs/formal.md §4.1 does not state the chain `Strength` defines; it must read: " + chain
    )


def test_the_authoring_docs_state_the_chain_the_code_defines():
    """The authoring documents' parenthetical enumerations of `Strength` members are
    generated from `sorted(Strength)`, so a rung added later cannot leave them behind.

    `recounted` once went missing from the `max_strength` field's parenthetical in
    `docs/authoring-engines.md`, and nothing in this generated-from-code family read the
    authoring documents at all.
    """
    chain = ", ".join(s.value for s in sorted(Strength))
    members = {s.value for s in Strength}
    for doc in (DOCS_DIR / "authoring-engines.md", DOCS_DIR / "authoring-packs.md"):
        for parenthetical in re.findall(r"\(([^()]*)\)", doc.read_text(encoding="utf-8")):
            names = [re.sub(r"[`\s]", "", n) for n in parenthetical.split(",")]
            names = [n for n in names if n]
            if len(names) > 1 and set(names) <= members:
                assert ", ".join(names) == chain, (
                    f"{doc.name} enumerates Strength members ({', '.join(names)}) but "
                    f"the lattice is {chain}"
                )


def test_the_formal_doc_states_the_requirement_field_count_the_code_defines():
    """§1.4's count sentence is generated from `Requirement`, not written from memory.

    The sentence once read twelve against the class's fifteen fields, and a prose number is
    exactly what this family exists to generate.
    """
    count = len(dataclasses.fields(Requirement))
    word = _NUMBER_WORDS[count]
    field_sentence = f"carries exactly {word} fields"
    assert field_sentence in _document() or field_sentence in MODELS.read_text(encoding="utf-8"), (
        "the models chapter or pending migration does not state the field count `Requirement` "
        "defines; "
        f"it must read: carries exactly {word} fields"
    )


def test_the_formal_doc_states_the_basis_rungs_the_code_defines():
    """§4.3's table is generated from `BASIS_RUNGS`, row by row.

    A row widened in the code and not here — or here and not in the code — is what this catches,
    and it is the table three module docstrings used to state in prose apiece.
    """
    document = _document()
    for basis, rungs in BASIS_RUNGS.items():
        row = f"| `{basis.value}` | " + ", ".join(f"`{r.value}`" for r in rungs) + " |"
        assert row in document, (
            f"docs/formal.md §4.3 does not carry the row for {basis.value}: {row}"
        )

    assert document.count("| Basis | Admits |") == 1, "§4.3's table is stated more than once"


def test_the_formal_doc_names_the_fragments_the_classifier_defines():
    """§2.9's classification order names exactly the fragments `rulelang` has, and no others."""
    section = _section("**Definition 2.6 (fragment assignment).**", SYNTAX)
    code = section[section.index("```") : section.index("```", section.index("```") + 3)]
    named = set(re.findall(r'"([a-z]+)"', code))
    assert named == set(FRAGMENTS), (
        "the syntax chapter names fragments the classifier does not have, or omits ones it does: "
        f"document {sorted(named)} vs code {sorted(FRAGMENTS)}"
    )


def test_the_formal_doc_names_the_algebras_the_code_defines():
    """§5.2's table names exactly `manyvalued.ALGEBRAS`, so a fourth member cannot be silent."""
    section = _section("**Definition 3.3 (the shipped algebras).**", SEMANTICS)
    rows = re.findall(r"^\| `([a-z]+)` \|", section, flags=re.MULTILINE)
    assert set(rows) == set(ALGEBRAS), (
        "docs/formal.md §5.2 does not name the algebras the code defines: "
        f"document {sorted(rows)} vs code {sorted(ALGEBRAS)}"
    )


def test_the_formal_doc_states_one_soundness_paragraph_per_engine():
    """§6 names every engine under `engines/`, so a new one cannot ship without a statement."""
    engines = sorted(
        p.stem for p in ENGINES_DIR.glob("*.py") if not p.stem.startswith("_")
    )
    assert engines, "no engine modules found; the directory this reads has moved"

    section = _document() + "\n" + PROCEDURES.read_text(encoding="utf-8")
    missing = [name for name in engines if f"`{name}`" not in section and name not in section]
    assert not missing, (
        "the decision-procedures chapter states no soundness paragraph for engine(s): "
        + ", ".join(missing)
    )


# ------------------------------------------------------------------------------------------------
# 3. The bibliography, as a registry
# ------------------------------------------------------------------------------------------------


def test_the_bibliography_has_entries_and_they_are_unique():
    """A registry with no entries, or with a key defined twice, enforces nothing."""
    lines = [
        line
        for line in BIBLIOGRAPHY.read_text(encoding="utf-8").splitlines()
        if _BIBLIOGRAPHY_ENTRY.match(line)
    ]
    keys = [_BIBLIOGRAPHY_ENTRY.match(line).group(1) for line in lines]
    assert keys, "docs/theory/bibliography.md defines no bibliography entry"
    duplicates = sorted({key for key in keys if keys.count(key) > 1})
    assert not duplicates, "the bibliography defines a key twice: " + ", ".join(duplicates)


def test_every_citation_key_resolves_to_a_bibliography_entry():
    """A citation anywhere in the corpus names an entry, so a typo is a failing build."""
    known = set(_bibliography_keys())
    unresolved: list[str] = []
    for path in _scanned_files():
        for key in set(_CITATION_KEY.findall(path.read_text(encoding="utf-8"))):
            if key not in known:
                unresolved.append(f"{path.relative_to(REPO_ROOT)}: [{key}]")
    assert not unresolved, (
        "citation key(s) with no bibliography entry in docs/theory/bibliography.md: "
        + ", ".join(sorted(unresolved))
        + ". Add the entry, or fix the key."
    )


def test_every_bibliography_entry_is_cited_by_a_claim():
    """A source nothing relies on leaves the list rather than accumulating in it."""
    entries = _bibliography_keys()
    cited: set[str] = set()
    for path in _scanned_files():
        for line in path.read_text(encoding="utf-8").splitlines():
            for key in _CITATION_KEY.findall(line):
                if key in entries and line != entries[key]:
                    cited.add(key)

    uncited = sorted(set(entries) - cited)
    assert not uncited, (
        "bibliography entr(ies) no claim cites: "
        + ", ".join(uncited)
        + ". Cite the work where it is relied on, or drop the entry."
    )


def test_a_source_named_without_a_key_is_refused():
    """A paragraph naming a venue and carrying no citation key is an unregistered source.

    This is the half of the registry that keeps references from drifting back into docstrings. It
    is a heuristic over `VENUE_MARKERS` and `docs/theory/bibliography.md` says so: a venue not on
    the list is a hole. The other two checks are not heuristics.
    """
    assert VENUE_MARKERS, "the marker list is empty, so this check passes vacuously"

    offenders: list[str] = []
    for path in _scanned_files():
        blocks = re.split(r"\n\s*\n", path.read_text(encoding="utf-8"))
        for block in blocks:
            if not any(marker in block for marker in VENUE_MARKERS):
                continue
            if _CITATION_KEY.search(block):
                continue
            first = next((line.strip() for line in block.splitlines() if line.strip()), "")
            offenders.append(f"{path.relative_to(REPO_ROOT)}: {first[:80]}")

    assert not offenders, (
        "a source is named without a citation key, so nothing registers it: "
        + "; ".join(sorted(offenders))
        + ". Add a `[key]` beside it and a bibliography entry in docs/theory/bibliography.md."
    )
